server:
  port: 8088

web:
  upload-path: F:/test/java/springboot2/src/main/resources/upload/
jwt:
  header: "Authorization" #token返回头部
  tokenPrefix: "Bearer " #token前缀
  secret: "peng123456" #密钥
  expireTime: 30 #token有效时间 (分钟) 建议一小时以上

spring:
  servlet:
    multipart:
      max-file-size: 100000KB  # ?????????????????????????
      max-request-size: 2MB # ?????????????